name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: ${{github.repository_owner == 'asnowc'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno install

      # - name: Publish-Jsr dry-run
      #   run: npx jsr publish --dry-run
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - name: Build
        run: npm exec --package=typescript@5 tsc

      - name: Publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Publish-Jsr
      #   run: npx jsr publish
